name: Publish Package to npmjs
on:
    push:
        tags:
            - '**'

jobs:
    read_tags:
        runs-on: ubuntu-latest
        steps:
            - name: Get Ref
              run: |
                  echo ref = ${{ github.ref }}
                  echo ref_name = ${{ github.ref_name }}
                  echo ref_protected = ${{ github.ref_protected }}
    # ci:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3

    #         - name: Installing Dependencies
    #           run: yarn

    #         - name: Build
    #           run: yarn build

    #         - name: Pre-Publish
    #           run: yarn prepublishOnly
    # publish:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3

    #         - name: Setting Up .npmrc file to publish to npm
    #           run: node ./bin/generate-npmrc.js
    #           env:
    #               NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    #         - name: Installing Dependencies
    #           run: yarn

    #         - name: Build
    #           run: yarn build

    #         - name: Pre-Publish
    #           run: yarn prepublishOnly

    #         - name: Copy PackageJson
    #           run: node ./bin/copy-package-json.js

    #         - name: Publishing
    #           run: cd ./dist && npm publish --access public
    #           env:
    #               NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    create_github_release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: rlespinasse/github-slug-action@v4.x

            # Get the last release tag
            - id: latestTag
              name: Get latest Release by tag
              uses: cardinalby/git-get-release-action@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  latest: true

            # Generate the Release's Changelog
            - name: Generate Changelog
              id: changelog
              uses: metcalfc/changelog-generator@v4.1.0
              with:
                  myToken: ${{ secrets.GITHUB_TOKEN }}
                  head-ref: ${{ steps.latestTag.outputs.tag_name }}
                  base-ref: ${{ github.ref_name }}

            - name: Creating Update Release
              uses: ncipollo/release-action@v1.13.0
              with:
                  body: |
                      Changes in this Release:
                      ${{ steps.changelog.outputs.changelog }}
                  commit: 'main'
                  tag: ${{ github.ref_name }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: '${{ github.ref_name }}'
                  allowUpdates: true
